CIT/CIT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cit2020.urls')),
    path('auth/', include('django.contrib.auth.urls')), 
    path('oauth/', include('social_django.urls', namespace='social')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CIT/cit2020/urls.py
from django.urls import path
from . import views

app_name='cit2020'
urlpatterns = [
    path('', views.index, name='index'),
    path('answer/<int:q_no>', views.answer , name='answer'),
    path('lboard/<int:slot>', views.lboard , name='lboard'),
    path('lboard/', views.lboard , name='lboard'),
    path('rules/', views.rules , name='rules'),
    path('about/', views.about , name='about'),
    path('forms/', views.forms , name='forms'),
    path('profile/', views.view_profile , name='view_profile'),
    path('profile/update', views.update_profile , name='update_profile'),
    path('qualify/<int:cutoff>', views.qualify , name='qualify'),
    path('finalize_rank/', views.finalize_rank , name='finalize_rank'),
]

CIT/templates/about.html
{%extends 'base.html'%}
{% load static %} 
{% block content %}

<style>
.social_icon .container {
  font-family: "Cabin", sans-serif;
  background-color: white;
  margin-top: 30px;
  padding-top: 20px;
  padding-bottom: 20px;
  display: flex;
  align-items: center;
  justify-content: space-around;
}
</style>

<div class="section section1">
    <div class="container">
        <h1 class="title"> <strong> Cognitive Intelligence Test 5.0 </strong> </h1>
        <p style="font-weight: bold;">
            Cognitive Intelligence test is the newest member in the chapter's list of
            events. It is an online event where sets of questions are designed similar
            to that of a screening process in company.CIT not only provides an idea
            about the level of competition but also gives a chance to rectify oneself.
            The test comprises of basic mathematical aptitude, verbal and logical
            reasoning and data interpretation. This is one of the finest opportunities
            to test one's skills and be better before the ultimate showdown.
        </p>
        </div>
</div>

<div class="social_icon">
    <div class="container">
        <div style="text-align: center;">
            <h3>Follow Us On !!</h3>
                <!-- <p id="demo">START!</p> -->
                <a href="https://www.facebook.com/istenitdgp/" target='_blank'><i class="fab fa-facebook-f fa-2x me-3" style="color: #3b5998;"></i></a>
                <a href="https://www.instagram.com/istenitdgp/" target='_blank'><i class="fab fa-instagram fa-2x me-3" style="color: #ac2bac;"></i></a>
                <a href="https://www.linkedin.com/company/istenitdgp/" target='_blank'><i class="fab fa-linkedin-in fa-2x me-3" style="color: #0082ca;"></i></a>
                
    </div>
</div>
</div>

<div class="section prizes-section">
    <div class="container">
        <div class="col-lg-12 ">
            <h2><strong>Cash PRIZES worth Rs. 7.5K For CIT 5.0</strong></p>
                <img src="{% static 'img/prize1.jpeg'%}" alt="PRIZES">
        </div>
    </div>
</div>

<div class="section section1">
    <div class="container">
        <h2><strong>Schedule For CIT 5.0</strong></h2>    
            <b>Qualifier Round:</b> Candidates can attempt CIT only once in any of the three available slots:
            <li><b>Slot 1:</b> January 18, 2021 (7:00 PM - 7:45 PM)</li>
            <li><b>Slot 2:</b> January 19, 2021 (7:00 PM - 7:45 PM)</li>
            <li><b>Slot 3:</b> January 20, 2021 (8:00 PM - 8:45 PM)</li>
            <b>Final Round:</b> Candidates selected for final round will receive a mail with details
            <li><b>Final:</b> January 22, 2021 (8:00 PM - 8:45 PM)</li>
        </div>
</div>

<div class="section sponsors-section">
    <div class="container">
        <div class="col-lg-12 ">
            <h2><strong>EVENT SPONSOR</strong></p>
                <img src="{% static 'img/ims.png'%}" alt="IMS"
                    style="margin-right: 10px; padding-bottom: 0;">
                <!-- <img src="{% static 'img/iocl.png'%}" alt="IOCL"
                    style="padding-bottom: 0;"> -->
        </div>
    </div>
</div>

{%endblock%}

CIT/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="CIT 2021 ISTE NIT Durgapur" />
  <meta name="author" content="" />

  <title>Cognitive Intelligence Test 5.0</title>

  <link rel="icon" href="{% static 'img/iste_new_logo.jpg'%}" type="image/x-icon" />

  <!-- bootstrap css -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />

  <!-- navbar syle files -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  <!-- custom css styles -->
  <link rel="stylesheet" href="{% static 'css/question-styles.css' %}" />
  <link rel="stylesheet" href="{% static 'css/complete-styles.css' %}" />

  <!-- fonts  -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cabin+Sketch:wght@700&display=swap" rel="stylesheet">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cabin:wght@500&display=swap" rel="stylesheet">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
</head>

<body>
  <div class="wrapper">
    <nav>
      <p class="Logo"><a href="{% url 'cit2020:index' %}">Cognitive Intelligence Test</a></p>
      <input type="checkbox" name="" class="btn" />
      <div class="nav">
        <ol>
          <li><a href="http://istenitdgp.com/" target='_blank'>ISTE</a></li>
          {% if "/" == request.path %}
          {% else %}
          <li><a href="{% url 'cit2020:index' %}">CIT</a></li>
          {% endif %}
          <li><a href="{% url 'cit2020:rules' %}">Rules</a></li>
          <li><a href="{% url 'cit2020:lboard' %}">Leaderboard</a></li>

          {% if user.is_anonymous %}
          <li><a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">G-Login</a></li>
          {% endif %}
          {% if user and not user.is_anonymous %}
          <li><a href="{% url 'cit2020:about' %}">About</a></li>
          <li class="drop-down">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
              {{ user.get_full_name|default:user.username }}
              <b class="caret"></b>
            </a>
            <div class="dropdown-content">
              <div class="d-content">
                <a href="{% url 'cit2020:view_profile' %}"><b>Profile</b></a>
                <a href="{% url 'logout' %}?next={{ '/' }}"><b>Logout</b></a>
              </div>
            </div>
          </li>
          {% endif %}
        </ol>
      </div>
    </nav>


    {% block content %} {% endblock %}

    <footer class="footer">
      <div class="line">
        <hr>
      </div>
      <p style="color: #111a2d">
        <strong>Developed by : </strong> ISTE NIT Durgapur, Students' Chapter
      </p>
      <!--<img src="{% static 'img/iste_logo2.png'%}" alt="iste_logo" style="border-radius: 50%;">-->
      <img src="{% static 'img/iste_new_logo.jpg'%}" alt="iste_logo" style="border-radius: 50%" />
      <img src="{% static 'img/nit_logo-min.png'%}" alt="iste_logo" style="border-radius: 50%" />
      <!--<img src="{% static 'img/nitdgp_logo1.png'%}" alt="nitdgp_logo" style="border-radius: 30%;">-->
    </footer>
  </div>



  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>

</body>

</html>

CIT/templates/finish.html
{% extends 'base.html' %}
{%block content%}

<div class="finish-section">
    <div class="container">
        {% if user and not user.is_anonymous %}
         <h2><strong>TEST FINISHED</strong></h2>
         <br>
         {% if player.qualified == True %}
         <h2 ><strong>Your Qualifier Round Score is {{player.score}} and Final Round Score is {{player.final_score}}</strong></h2>
         <br><br>
        <h2 ><strong>Visit <a style="text-decoration:none;" href="{% url 'cit2020:lboard' %}"> LEADERBOARD </a> for Rank</strong></h2>
        {% else %}
        <h2 ><strong>Your Qualifier Round Score is {{player.score}}</strong></h2>
         <br><br>
        <h2 ><strong>Visit <a style="text-decoration:none;" href="{% url 'cit2020:lboard' slot=player.slot %}"> LEADERBOARD </a> for Rank</strong></h2>
        {% endif %}
	{% endif %}
    </div>
</div>

{%endblock%}

CIT/templates/forms.html
{% extends 'base.html' %} {% block content %}

<div class="slots-choose">
  <div class="container">

    <h2>Please Choose Your Slot for Qualifier Round - </h2>

    <form id="slot" method="post" action="/forms/">
      {% csrf_token %}
      <div class="options-block slots-block">
        <div class="opt">
          <input type="radio" name="slot" value="1" id="slot1" />
          <label for="slot1">18 January 2022 (7:00 PM - 7:45 PM)</label>
        </div>
        <div class="opt">
          <input type="radio" name="slot" value="2" id="option2" />
          <label for="option2">19 January 2022 (7:00 PM - 7:45 PM)</label>
        </div>
        <div class="opt">
          <input type="radio" name="slot" value="3" id="option3" />
          <label for="option3">20 January 2022 (8:00 PM - 8:45 PM)</label>
        </div>
      </div>
      <br> <br>
      <div class="next-arrow-block">
        <div class="next-arrow">
          <input type="submit" value="Submit &#8594 " />
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

CIT/templates/index_page.html
{%extends 'base.html'%}
{% load static %} 
{% block content %}

<div class="section section1">
    <div class="container">
        <h1 class="title"> <strong> Cognitive Intelligence Test 5.0 </strong> </h1>
        <p style="font-weight: bold;">
            Cognitive Intelligence test is the newest member in the chapter's list of
            events. It is an online event where sets of questions are designed similar
            to that of a screening process in company.CIT not only provides an idea
            about the level of competition but also gives a chance to rectify oneself.
            The test comprises of basic mathematical aptitude, verbal and logical
            reasoning and data interpretation. This is one of the finest opportunities
            to test one's skills and be better before the ultimate showdown.
        </p>
        <h2><strong>Schedule For CIT 5.0</strong></h2>    
            <b>Qualifier Round:</b> Candidates can attempt CIT only once in any of the three available slots:
            <li><b>Slot 1:</b> January 18, 2021 (7:00 PM - 7:45 PM)</li>
            <li><b>Slot 2:</b> January 19, 2021 (7:00 PM - 7:45 PM)</li>
            <li><b>Slot 3:</b> January 20, 2021 (8:00 PM - 8:45 PM)</li>
            <b>Final Round:</b> Candidates selected for final round will receive a mail with details
            <li><b>Final:</b> January 22, 2021 (8:00 PM - 8:45 PM)</li>
        </div>
</div>

<div class="section2">
    <div class="container">
        <div class="count-down">
            <h3><strong>Count Down</strong></h3>
                <p id="demo">START!</p>
        </div>
        <div class="login">
            {% if final_started %}
            <h3>Login to Start Quiz!</h3><br>
            {% else %}
            <h3>Login to Book Slot for Qualifier Round !</h3><br>
            {% endif %}
            <button class="login-button" onclick="window.location='{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}';">Login With Google</button>
        </div>
    </div>
</div>

<div class="section prizes-section">
    <div class="container">
        <div class="col-lg-12 ">
            <h2><strong>Cash PRIZES worth Rs. 7.5K For CIT 5.0</strong></p>
                <img src="{% static 'img/prize1.jpeg'%}" alt="PRIZES">
        </div>
    </div>
</div>
<div class="rules-section">
    <div class="container">
        <h2><strong>RULES</strong></h2>
        <ul>
            <li>Register at <a href="https://dare2compete.com/competition/cognitive-intelligence-test-50-national-institute-of-technology-nit-durgapur-253760" target='_blank' style="text-decoration: none;">Dare2Compete</a> platform to confirm your registration.</li>
            <li>This test comprises of <strong>30 questions</strong> which needs to be solved in
                time limit of <strong>45 minutes</strong>.</li> 
            <li>Test includes questions from Logical Reasoning, Verbal Reasoning, Data Interpretation and Aptitude.
                </li>
            <li>Each question carries <strong>4 mark for correct answer. Incorrect
                    answer will fetch you negative marks of - 1.</strong></li>
            <li>No marks if question is not attempted.</li>
            <li><strong>Just Select the Option or Click Next Question(without
                    selecting any option) to skip the Question</strong></li>
            <li>Once you skip to the next question you cannot go back.</li>
        </ul>
    </div>
</div>

<div class="section sponsors-section">
    <div class="container">
        <div class="col-lg-12 ">
            <h2><strong>EVENT SPONSOR</strong></p>
                <img src="{% static 'img/ims.png'%}" alt="IMS"
                    style="margin-right: 10px; padding-bottom: 0;">
                <!-- <img src="{% static 'img/iocl.png'%}" alt="IOCL"
                    style="padding-bottom: 0;"> -->
        </div>
    </div>
</div>

<script>
    // Set the date we're counting down to
    var countDownDate = new Date("Jan 18, 2022 19:00:00").getTime();
    
    // Update the count down every 1 second
    var x = setInterval(function() {
    
      // Get today's date and time
      var now = new Date().getTime();
    
      // Find the distance between now and the count down date
      var distance = countDownDate - now;
    
      // Time calculations for days, hours, minutes and seconds
      var days = Math.floor(distance / (1000 * 60 * 60 * 24));
      var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
      var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    
      // Display the result in the element with id="demo"
      document.getElementById("demo").innerHTML = days + "d " + hours + "h "
      + minutes + "m " + seconds + "s ";
    
      // If the count down is finished, write some text
      if (distance < 0) {
        clearInterval(x);
        document.getElementById("demo").innerHTML = "START!";
      }
    }, 1000);
    </script>

{%endblock%}

CIT/templates/lboard.html
{%extends 'base.html'%}

{%block content%}
<div class="slots">
    <div class="container">
        <a class="slot-button" href="{% url 'cit2020:lboard' 1  %}">Slot 1</a>
        <a class="slot-button" href="{% url 'cit2020:lboard' 2  %}">Slot 2</a>
        <a class="slot-button" href="{% url 'cit2020:lboard' 3  %}">Slot 3</a>
        <a class="slot-button" href="{% url 'cit2020:lboard' 4 %}">Final Round</a>
     
    </div>
       
</div>

<div class="table-section">
    <div class="container">
        <h1 style="text-decoration: underline; text-decoration-style: dotted;"><strong> Leaderboard 

            {% if slot == 1 %} - Slot 1
            {% elif slot == 2 %} - Slot 2
            {% elif slot == 3 %} - Slot 3
            {% else %} - Final
            {% endif %}

        </strong></h1>
        {% if players %}
        {% if rank == 0 %}
        {% else %}
        <h4 style="text-align: center;"><strong> Your rank is {{rank}} </strong></h4>
        {% endif %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Rank</th>
                    <th scope="col">Name</th>
                    <th scope="col">Score</th>
                </tr>
            </thead>
            <tbody>
                {% if is_final == True %}
                    {% for player in players %}
                    {% if rank == player.rank %}
                    <tr class="highlight-rank" >
                        <td scope="row">{{ player.rank }}</td>
                        <td>{{ player.name }}</td>
                        <td>{{player.final_score}}</td>
                    </tr>
                    {% else %}
                    <tr>
                        <td scope="row">{{ player.rank }}</td>
                        <td>{{ player.name }}</td>
                        <td>{{player.final_score}}</td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                {% else %}
                    {% for player in players %}
                    {% if rank == player.rank %}
                    <tr class="highlight-rank" >
                        <td scope="row">{{ player.rank }}</td>
                        <td>{{ player.name }}</td>
                        <td>{{player.score}}</td>
                    </tr>
                    {% else %}
                    <tr>
                        <td scope="row">{{ player.rank }}</td>
                        <td>{{ player.name }}</td>
                        <td>{{player.score}}</td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
        {%else  %}
        <h1><strong> Leaderboard will be available soon ....  </strong></h1>
        {% endif %}

    </div>
</div>

{%endblock%}

CIT/templates/luck.html
{% extends 'base.html' %}
{%block content%}

<div class="luck-section">
    <div class="container">
        <h2><strong>You Have Not Qualified For the Final Round</strong></h2>
        <h2><strong>Your score is {{player.score}} which is less than cutoff</strong></h2>
        <br><br><br>
        <h3><strong>Keep Practicing , Meet You In CIT 6.0</strong></h3>
    </div>
</div>

{%endblock%}

CIT/templates/question.html
{% extends 'base.html' %}

{%block content%}

<div class="timer-section">
    <div class="container" id="demo-box">
        <p id="demo" class="time-left"></p>
    </div>
</div>

<div class="question-section">
    <div class="container">
        <p style="font-family: 'Cabin', sans-serif;font-weight: 200;font-size:24px;color:#111a2d">Question Accuracy:
            {{question.accuracy}} %</p>

        <div class="question" style="user-select:none;-webkit-user-select:none;-moz-user-select:none;-o-user-select:none;-user-select:none;" >
            <strong>Q {{question.Q_number}} :- </strong><br>
            {{ question.Question|safe }}
        </div>
        
        {% if question.image %}

    <div class="image-section">
      <img src="{{question.image.url}}" width="100%"/>
    </div>

  {%endif%}

        <form id="ans" method="post" action="{% url 'cit2020:answer' q_no=question.Q_number %}">
            {% csrf_token %}
            <div class="options-block">
                <div class="opt">
                    <input type="radio" name="option" value="1" id="option1">
                    <label for="option1" style="user-select:none;-webkit-user-select:none;-moz-user-select:none;-o-user-select:none;-user-select:none;">{{question.option1}}</label>
                </div>
                <div class="opt">
                    <input type="radio" name="option" value="2" id="option2">
                    <label for="option2" style="user-select:none;-webkit-user-select:none;-moz-user-select:none;-o-user-select:none;-user-select:none;">{{question.option2}}</label>
                </div>
                <div class="opt">
                    <input type="radio" name="option" value="3" id="option3">
                    <label for="option3" style="user-select:none;-webkit-user-select:none;-moz-user-select:none;-o-user-select:none;-user-select:none;">{{question.option3}}</label>
                </div>
                <div class="opt">
                    <input type="radio" name="option" value="4" id="option4">
                    <label for="option4" style="user-select:none;-webkit-user-select:none;-moz-user-select:none;-o-user-select:none;-user-select:none;">{{question.option4}}</label>
                </div>
                <span style="display:none"><input type="radio" name="option" id="option5" value="0" /></span>
                <input type="button" class="clear-button" value="Clear Choice"
                    onclick="document.getElementById('option5').checked = true;" />

            </div>
            <div class="next-arrow-block">
                <div class="next-arrow">
                    <input type="submit" value="Next &#8594" />
                </div>

            </div>

        </form>
    </div>
</div>

<script>
    // Set the date we're counting down to
    True = 1
      False=0
      var countDownDate
      if ({{player.qualified}}) {
        // Final slot date
        countDownDate = new Date("Jan 22, 2022 20:45:00").getTime();
      }
      else if ({{player.slot}}==1) {
        // slot 1 date
        countDownDate = new Date("Jan 18, 2022 19:45:00").getTime();
      } 
      else if ({{player.slot}}==2) {
        // slot 2 date 
        countDownDate = new Date("Jan 19, 2022 19:45:00").getTime();
      } 
      else if ({{player.slot}}==3) {
        // slot 3 date 
        countDownDate = new Date("Jan 20, 2022 20:45:00").getTime();
      } 
      else{
        // final slot date 
        countDownDate = new Date("Jan 22, 2022 20:45:00").getTime();
      }

    // Update the count down every 1 second
    var x = setInterval(function () {

        // Get today's date and time
        var now = new Date().getTime();

        // Find the distance between now and the count down date
        var distance = countDownDate - now;

        // Time calculations for days, hours, minutes and seconds
        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);

        // Display the result in the element with id="demo"
        document.getElementById("demo-box").style.visibility = "visible";
        document.getElementById("demo").innerHTML = "Time Left : " + hours + "h "
            + minutes + "m " + seconds + "s ";

        // If the count down is finished, write some text
        if (distance < 0) {
            clearInterval(x);
            document.getElementById("demo").innerHTML = "TIME OVER";
            // window.location.replace("/lboard");
            document.getElementById("ans").submit();
            // window.location.reload();
        }
        else if(hours == 0 && minutes == 5 && seconds == 0)
        {
            alert("Quiz will auto-submit after 5 minutes");
        }
    }, 1000);
</script>


{%endblock%}

CIT/templates/view_profile.html
{% extends 'base.html' %} {% block content %}
{% load widget_tweaks %}

<div class="view-profile">
  <div class="container">
    <br>
    <h1>Your Profile :- </h1>
    <br>
    <div class="row">
    <div class="col-md-12 col-lg-6 mb-2">
        <h4><strong>Name : </strong> {{player.name}}</h4>  
        <h4><strong>Email Id : </strong> {{player.email}}</h4>
        <h4><strong>Mobile No : </strong> {{player.mobile}}</h4>
        <h4><strong>School/College : </strong> {{player.institute_name}}</h4>
        <h4><strong>Year of Study : </strong> {{player.year_of_study}}</h4>
        {% if player.department %}
        <h4><strong>Department : </strong> {{player.department}}</h4>
        {% endif %}
    </div>
    <div class="col-md-12 col-lg-6 mb-2">
        {% if player.slot == 0 %}
        <h3><strong>Preliminary Round : </strong>Select <a href="{% url 'cit2020:index' %}"><strong>Slot</strong></a></h3>
        {% else %}
        <h3><strong>Qualifier Round : </strong></h3>
        <h4><strong>Slot: </strong> 
            {% if player.slot == 1 %} (1) Jan 18, 2021 (7:00 PM - 7:45 PM)
            {% elif player.slot == 2 %} (2) Jan 19, 2021 (7:00 PM - 7:45 PM)
            {% elif player.slot == 3 %} (3) Jan 20, 2021 (8:00 PM - 8:45 PM)
            {% endif %}
        </h4>
        <h4><strong>Score : </strong> {{player.score}}</h4>
        {% if final == False %}
        <h4><strong>Selected for Final : </strong> -- </h4>
        {% elif player.qualified == True %}
        <h4><strong>Selected for Final : </strong> Yes </h4>
        {% else %}
        <h4><strong>Selected for Final : </strong> No </h4>
        {% endif %}
        {% if player.qualified == True %}
        <h3><strong>Final Round : </strong></h3>
        <h4><strong>Slot : </strong> Jan 22, 2021 (8:00 PM - 8:45 PM)</h4>
        <h4><strong>Score : </strong> {{player.final_score}}</h4>
        {% endif %}
        {% endif %}    
    </div>
    </div>
  </div>
</div>

{% endblock content %}

CIT/templates/win.html
{% extends 'base.html' %}

{%block content%}

<div class="win-section">
    <div class="container">
        <h2><strong>You Have Attempted All Questions</strong></h2>
        <br>
        {% if player.qualified == True %}
         <h2 ><strong>Your Qualifier Round Score is {{player.score}} and Final Round Score is {{player.final_score}}</strong></h2>
         <br><br>
        <h2 ><strong>Visit <a style="text-decoration:none;" href="{% url 'cit2020:lboard' %}"> LEADERBOARD </a> for Rank</strong></h2>
        {% else %}
        <h2 ><strong>Your Qualifier Round Score is {{player.score}}</strong></h2>
         <br><br>
        <h2 ><strong>Visit <a style="text-decoration:none;" href="{% url 'cit2020:lboard' slot=player.slot  %}"> LEADERBOARD </a> for Rank</strong></h2>
        {% endif %}
    </div>
</div>

{%endblock%}